-- MySQL Script generated by MySQL Workbench
-- Wed 02 Nov 2016 08:22:32 AM ART
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema u140857914_aguas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema u140857914_aguas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u140857914_aguas` DEFAULT CHARACTER SET utf8 ;
USE `u140857914_aguas` ;

-- -----------------------------------------------------
-- Table `u140857914_aguas`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u140857914_aguas`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u140857914_aguas`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u140857914_aguas`.`localidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `provincia` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u140857914_aguas`.`planta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u140857914_aguas`.`planta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `planta` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  `localidad_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `localidad_id`),
  INDEX `fk_planta_usuario_idx` (`usuario_id` ASC),
  INDEX `fk_planta_localidad1_idx` (`localidad_id` ASC),
  CONSTRAINT `fk_planta_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `u140857914_aguas`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planta_localidad1`
    FOREIGN KEY (`localidad_id`)
    REFERENCES `u140857914_aguas`.`localidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u140857914_aguas`.`salida_planta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u140857914_aguas`.`salida_planta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `caudal` VARCHAR(45) NOT NULL,
  `turbiedad_entrada` VARCHAR(45) NOT NULL,
  `turbiedad_salida` VARCHAR(45) NOT NULL,
  `cloro_residual` VARCHAR(45) NOT NULL,
  `color_test` VARCHAR(45) NULL,
  `fecha_hora` DATETIME NOT NULL,
  `planta_id` INT NOT NULL,
  `planta_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `planta_id`, `planta_usuario_id`),
  INDEX `fk_salida_planta_planta1_idx` (`planta_id` ASC, `planta_usuario_id` ASC),
  CONSTRAINT `fk_salida_planta_planta1`
    FOREIGN KEY (`planta_id` , `planta_usuario_id`)
    REFERENCES `u140857914_aguas`.`planta` (`id` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u140857914_aguas`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u140857914_aguas`.`stock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sulfato` VARCHAR(45) NULL,
  `hipoclorito` VARCHAR(45) NULL,
  `polielectrolito` VARCHAR(45) NULL,
  `fecha_hora` DATETIME NOT NULL,
  `planta_id` INT NOT NULL,
  `planta_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `planta_id`, `planta_usuario_id`),
  INDEX `fk_stock_planta1_idx` (`planta_id` ASC, `planta_usuario_id` ASC),
  CONSTRAINT `fk_stock_planta1`
    FOREIGN KEY (`planta_id` , `planta_usuario_id`)
    REFERENCES `u140857914_aguas`.`planta` (`id` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u140857914_aguas`.`stock_salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u140857914_aguas`.`stock_salida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sulfato` VARCHAR(45) NULL,
  `hipoclorito` VARCHAR(45) NULL,
  `polielectrolito` VARCHAR(45) NULL,
  `fecha_hora` DATETIME NOT NULL,
  `planta_id` INT NOT NULL,
  `planta_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `planta_id`, `planta_usuario_id`),
  INDEX `fk_stock_salida_planta1_idx` (`planta_id` ASC, `planta_usuario_id` ASC),
  CONSTRAINT `fk_stock_salida_planta1`
    FOREIGN KEY (`planta_id` , `planta_usuario_id`)
    REFERENCES `u140857914_aguas`.`planta` (`id` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `u140857914_aguas`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `u140857914_aguas`;
INSERT INTO `u140857914_aguas`.`usuario` (`id`, `user`, `password`, `mail`, `telephone`) VALUES (1, 'mceliz', 'Seighei7', 'mceliz@enlaceit.com.ar', '2996739666');
INSERT INTO `u140857914_aguas`.`usuario` (`id`, `user`, `password`, `mail`, `telephone`) VALUES (2, 'jmelicabe', 'limoo1Ae', 'jmelicabe@aguasrionegrinas.com.ar', NULL);
INSERT INTO `u140857914_aguas`.`usuario` (`id`, `user`, `password`, `mail`, `telephone`) VALUES (3, 'cceliz', 'pangoD3f', 'celizmartin_claudio@hotmail.com', NULL);
INSERT INTO `u140857914_aguas`.`usuario` (`id`, `user`, `password`, `mail`, `telephone`) VALUES (4, 'colorado', 'Chohj4Ae', 'colorado@aguasrionegrinas.com.ar', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `u140857914_aguas`.`localidad`
-- -----------------------------------------------------
START TRANSACTION;
USE `u140857914_aguas`;
INSERT INTO `u140857914_aguas`.`localidad` (`id`, `provincia`, `localidad`) VALUES (1, 'RIO NEGRO', 'CIPOLLETTI');
INSERT INTO `u140857914_aguas`.`localidad` (`id`, `provincia`, `localidad`) VALUES (2, 'RIO NEGRO', 'RIO COLORADO');

COMMIT;


-- -----------------------------------------------------
-- Data for table `u140857914_aguas`.`planta`
-- -----------------------------------------------------
START TRANSACTION;
USE `u140857914_aguas`;
INSERT INTO `u140857914_aguas`.`planta` (`id`, `planta`, `usuario_id`, `localidad_id`) VALUES (1, 'Planta Potabilizadora Principal', 3, 1);
INSERT INTO `u140857914_aguas`.`planta` (`id`, `planta`, `usuario_id`, `localidad_id`) VALUES (2, 'Filtros Canal ', 3, 1);
INSERT INTO `u140857914_aguas`.`planta` (`id`, `planta`, `usuario_id`, `localidad_id`) VALUES (3, 'Planta Potabilizadora Principal', 4, 2);
INSERT INTO `u140857914_aguas`.`planta` (`id`, `planta`, `usuario_id`, `localidad_id`) VALUES (4, 'Planta Potabilizadora Buena Parada', 4, 2);

COMMIT;

